# Development:
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Simply Jetpacks:
mod_version=3.0.0

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=simplyjetpacks
# The human-readable display name for the mod.
mod_name=Simply Jetpacks 2
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT License

# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=tomson124.simplyjetpacks

# Minecraft/Forge:
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.217
loader_version_range=[1,)

# Mod Dependencies:
#jei_version=15.16.2.73
#top_version=1.17-4.0.2
#curios_version=5.9.1
#configured_version=1.5.0
#patchouli_version=1.17.1-57

# TODO: check these
#mekanism_version=10.1.1.456
#immersiveengineering_version=1.16.5-5.0.7-143
#thermal_version=1.4.1